# Generated by Django 5.1.4 on 2026-06-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opiniones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='opiniones/'),
        ),
    ]
